# Generated by Django 5.1 on 2024-09-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_attendance_remove_enrollment_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='gallery/')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
